plugins {
    id 'java'
}

group = 'slidingGame'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

sourceSets {
    main {
        java.srcDirs = ['src']
    }
    test {
        java.srcDirs = ['test']
    }
}

test {
    useJUnit()
}